name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: discord-music-bot-rs
      TARGET: x86_64-unknown-linux-musl
      OS: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Install and configure dependencies
        run: |
          # dependencies are only needed on ubuntu as that's the only place where
          # we make cross-compilation
          if [[ $OS =~ ^ubuntu.*$ ]]; then
            sudo apt-get install -qq musl-tools libssl-dev
          fi
      - name: install rust target
        run: rustup target add $TARGET
      - name: Build
        run: cargo build --verbose --target $TARGET
      - name: Run tests
        run: cargo test --verbose
      - name: Archive debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: discord-music-bot-rs-linux-debug
          path: target/debug/discord-music-bot-rs

  build-release:
    runs-on: ubuntu-latest
    env:
      NAME: discord-music-bot-rs
      TARGET: x86_64-unknown-linux-musl
      OS: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Install and configure dependencies
        run: |
          # dependencies are only needed on ubuntu as that's the only place where
          # we make cross-compilation
          if [[ $OS =~ ^ubuntu.*$ ]]; then
            sudo apt-get install -qq musl-tools libssl-dev
          fi
      - name: install rust target
        run: rustup target add $TARGET
      - name: Build
        run: cargo build --release --verbose --target $TARGET
      - name: Archive release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: discord-music-bot-rs-linux
          path: target/release/discord-music-bot-rs
